version: '3.8'

services:
  gna-customers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gna-customers-service
    ports:
      - "8091:8091"  # Adapte si besoin
    env_file:
      - .env
    restart: always
