export enum AiSuggestionType {
  BOOK_PLAN = 'BOOK_PLAN',
  CHAPTER_DRAFT = 'CHAPTER_DRAFT',
  SENTENCE_SUGGESTION = 'SENTENCE_SUGGESTION',
  CORRECTION = 'CORRECTION',
  NARRATIVE_ADVICE = 'NARRATIVE_ADVICE',
  COVER_PROMPT = 'COVER_PROMPT',
}

export enum MediaType {
  AUDIO_NARRATION = 'AUDIO_NARRATION',
  VIDEO_STORY = 'VIDEO_STORY',
}

export enum VoiceGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NEUTRAL = 'NEUTRAL',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  FAILED = 'FAILED',
}